/*
----- INFORMATION ----- INFORMATION ----- INFORMATION ----- INFORMATION ----- INFORMATION ----- INFORMATION 

THIS IS THE MAIN FILE OF THE BOT.
DO NOT MODIFY THIS.

- THIS FILE IS ONLY NEEDED FOR INIT. THE BOT AND THE DATABASE CONNECTION

- SUPPORT IS NOT PROVIDED IF THIS IS MODIFIED/CHANGED/MOVED IN ANY WAY.


last update: 5/2/2022
*/




"use strict";

require("./src/util/bot.js");

require("./src/util/db.js");